In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB


In [2]:
pig1 = [1, 1, 0]
pig2 = [1, 1, 0]
pig3 = [1, 1, 0]
dog4 = [1, 1, 1]
dog5 = [0, 1, 1]
dog6 = [0, 1, 1]

index =  [pig1, pig2, pig3, dog4, dog5, dog6]
target = [1 , 1, 1, -1, -1, -1]



df = pd.DataFrame(np.array(index), columns=['Gordo', 'Perna curta', 'faz auau'])
df['target'] = target
df.iloc[:,3]

0    1
1    1
2    1
3   -1
4   -1
5   -1
Name: target, dtype: int64

In [3]:
model = MultinomialNB()
model.fit(df.iloc[:,:3].values, df.iloc[:,3].values)

MultinomialNB()

In [4]:
x1 = [1, 1, 1]
x2 = [1, 0, 0]
x3 = [0, 0 ,1]

y = [-1, 1, 1]


df_teste = pd.DataFrame(np.array([x1, x2, x3]), columns=['Gordo', 'Perna Curta', 'faz auau'])
df_teste['target'] = y
df_teste.iloc[:,:3].values

array([[1, 1, 1],
       [1, 0, 0],
       [0, 0, 1]])

In [5]:
result = model.predict(df_teste.iloc[:,:3].values)

In [6]:
diff  = result - y

In [7]:
hits = [d for d in diff if d ==0]


In [8]:
total_hits = len(hits)
total_element = len(y)

In [9]:
rate_hits = 100 * total_hits / total_element

In [10]:
result

array([-1,  1, -1])

In [11]:
diff

array([ 0,  0, -2])

In [12]:
rate_hits

66.66666666666667